"""empty message

Revision ID: 506125df523c
Revises: f8d25ffd649c
Create Date: 2023-05-24 14:11:32.387396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506125df523c'
down_revision = 'f8d25ffd649c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.alter_column('date_of_birth',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
